# Generated by Django 4.1.7 on 2023-03-15 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0002_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="Person_name",
        ),
    ]
