# Generated by Django 4.1.7 on 2023-03-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0003_rename_name_person_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
