# Generated by Django 4.1.7 on 2023-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0007_customer_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductID", models.IntegerField()),
                ("name", models.TextField()),
                ("category", models.TextField()),
            ],
            options={
                "permissions": [("can_change_category", "Can change category")],
            },
        ),
    ]
